version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports: 
      - '6379:6379'
  bot:
    container_name: junko
    restart: always
    build: .
    depends_on:
      - redis
    env_file:
      - .env