version: '3'
services:
  redis:
    image: redis:alpine
    networks:
      - junko_net
    restart: always
    logging:
      driver: "fluentd"
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
       - postgres:/var/lib/postgresql/data
    networks:
      - junko_net
    restart: always
    logging:
      driver: "fluentd"
  bot:
    build: ./src/bot
    env_file:
      - ./src/bot/.env
    volumes:
      - ./src/proto:/usr/src/proto
    ports:
      - '5000:5000'
    networks:
      - junko_net
    depends_on:
      - redis
      - postgres
    restart: always
    logging:
      driver: "fluentd"
  api:
    build: ./src/api
    env_file:
      - ./src/api/.env
    ports:
      - '4000:4000'
    networks:
      - junko_net
    restart: always
    logging:
      driver: "fluentd"
  dashboard:
    build: ./src/dashboard
    env_file:
      - ./src/dashboard/.env
    ports:
      - '8080:8080'
    networks:
      - junko_net
    restart: always
    logging:
      driver: "fluentd"

networks:
  junko_net:

volumes:
  postgres: