version: '3.4'

x-defaults: &defaults
  restart: unless-stopped
  networks:
    - main
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/api/prom/push"
  
services:
  bot:
    <<: *defaults
    image: hichuyamichu/junko-bot:latest
    env_file:
      - ./env/bot/.env
    volumes:
      - ./src/proto:/usr/src/proto
    
  api:
    <<: *defaults
    image: hichuyamichu/junko-api:latest
    env_file:
      - ./env/api/.env
    
  dashboard:
    <<: *defaults
    image: hichuyamichu/junko-dashboard:latest
    env_file:
      - ./env/dashboard/.env

networks:
  main:
    external: true
