FROM node:12-alpine

WORKDIR /usr/src/junko

COPY src/dashboard/package.json src/dashboard/package-lock.json /usr/src/junko/

RUN npm install

COPY src/dashboard /usr/src/junko/

RUN npm run build

EXPOSE 8080

CMD ["npm", "run", start"]