version: '3'
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    logging:
      driver: "fluentd"
  bot:
    container_name: bot
    restart: always
    build: ./src/bot
    env_file:
      - ./src/bot/.env
    volumes:
      - ./src/proto:/usr/src/proto
    ports:
      - '5000:5000'
    logging:
      driver: "fluentd"
  api:
    container_name: api
    restart: always
    build: ./src/api
    volumes:
      - ./src/proto:/usr/src/proto
    ports:
      - '4000:4000'
    logging:
      driver: "fluentd"
  dashboard:
    container_name: dashboard
    restart: always
    build: ./src/dashboard
    env_file:
      - ./src/dashboard/.env
    ports:
      - '8080:8080'
    logging:
      driver: "fluentd"
