FROM node:12-alpine

ENV TOKEN= \
YT_KEY= \
SPOTIFY_ID= \
SPOTIFY_SECRET= \
OWNER_ID= \
REDIS_URI= \
RPC_ADDR=

WORKDIR /usr/src/junko

COPY src/bot/package.json /usr/src/junko/src/bot/
COPY tsconfig.json package.json yarn.lock /usr/src/junko/
COPY src/proto /usr/src/junko/src/proto

RUN ls

RUN apk add --update \
&& apk add --no-cache pixman cairo pango giflib libjpeg-turbo \
&& apk add --no-cache --virtual .build-deps git curl build-base jpeg-dev pixman-dev \
cairo-dev pango-dev pangomm-dev libjpeg-turbo-dev giflib-dev freetype-dev python g++ make \
&& yarn install --build-from-source \
&& apk del .build-deps

COPY src/bot /usr/src/junko/src/bot/

WORKDIR /usr/src/junko/src/bot

RUN yarn build

EXPOSE 5000

CMD ["yarn", "start"]