FROM golang:latest AS build

WORKDIR /build

ENV GO111MODULE=on

COPY src/api/go.mod src/api/go.sum ./

RUN go mod download

COPY src/api ./

RUN go get -u github.com/gobuffalo/packr/packr

RUN CGO_ENABLED=0 GOOS=linux packr build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o junko-api main.go

FROM scratch

WORKDIR /app

COPY --from=build /build/junko-api /app/

EXPOSE 4000

CMD ["./junko-api", "-port=4000", "-host=0.0.0.0"]