FROM node:10-alpine

WORKDIR /usr/src/dashboard

COPY package.json ./
RUN yarn

ENV NUXT_HOST= \
  NUXT_PORT= \
  API_SERVER_SIDE= \
  API_CLIENT_SIDE=

COPY . .
RUN yarn build && yarn cache clean

EXPOSE 8080

CMD ["yarn", "start"]