const languages: [string, string[]][] = [
  ['apl', ['apl']],
  ['bash', ['bash', 'sh']],
  ['brainfuck', ['brainfuck', 'bf']],
  ['c', ['c']],
  ['clojure', ['clojure', 'clj']],
  ['cpp', ['cpp']],
  ['csharp', ['csharp', 'cs']],
  ['elixir', ['elixir']],
  ['erlang', ['erlang', 'erl']],
  ['fsharp', ['fsharp', 'fs']],
  ['go', ['golang', 'go']],
  ['haskell', ['haskell', 'hs']],
  ['idris', ['idris', 'idr']],
  ['java', ['java']],
  ['javascript', ['javascript', 'js']],
  ['julia', ['julia']],
  ['lua', ['lua']],
  ['ocaml', ['ocaml', 'ml']],
  ['pascal', ['pascal', 'pas', 'freepascal']],
  ['perl', ['perl', 'pl']],
  ['php', ['php']],
  ['prolog', ['prolog']],
  ['python', ['python', 'py']],
  ['racket', ['lisp']],
  ['ruby', ['ruby', 'rb']],
  ['rust', ['rust', 'rs']]
];

export { languages };
