// Code generated by protoc-gen-go. DO NOT EDIT.
// source: services.proto

package fetcher

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CategoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoriesRequest) Reset()         { *m = CategoriesRequest{} }
func (m *CategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*CategoriesRequest) ProtoMessage()    {}
func (*CategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{0}
}

func (m *CategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesRequest.Unmarshal(m, b)
}
func (m *CategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesRequest.Marshal(b, m, deterministic)
}
func (m *CategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesRequest.Merge(m, src)
}
func (m *CategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_CategoriesRequest.Size(m)
}
func (m *CategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesRequest proto.InternalMessageInfo

type CategoriesResponce struct {
	CategoryNames        []string `protobuf:"bytes,1,rep,name=categoryNames,proto3" json:"categoryNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoriesResponce) Reset()         { *m = CategoriesResponce{} }
func (m *CategoriesResponce) String() string { return proto.CompactTextString(m) }
func (*CategoriesResponce) ProtoMessage()    {}
func (*CategoriesResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{1}
}

func (m *CategoriesResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoriesResponce.Unmarshal(m, b)
}
func (m *CategoriesResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoriesResponce.Marshal(b, m, deterministic)
}
func (m *CategoriesResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoriesResponce.Merge(m, src)
}
func (m *CategoriesResponce) XXX_Size() int {
	return xxx_messageInfo_CategoriesResponce.Size(m)
}
func (m *CategoriesResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoriesResponce.DiscardUnknown(m)
}

var xxx_messageInfo_CategoriesResponce proto.InternalMessageInfo

func (m *CategoriesResponce) GetCategoryNames() []string {
	if m != nil {
		return m.CategoryNames
	}
	return nil
}

type CommandsRequest struct {
	CategoryName         string   `protobuf:"bytes,1,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandsRequest) Reset()         { *m = CommandsRequest{} }
func (m *CommandsRequest) String() string { return proto.CompactTextString(m) }
func (*CommandsRequest) ProtoMessage()    {}
func (*CommandsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{2}
}

func (m *CommandsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandsRequest.Unmarshal(m, b)
}
func (m *CommandsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandsRequest.Marshal(b, m, deterministic)
}
func (m *CommandsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandsRequest.Merge(m, src)
}
func (m *CommandsRequest) XXX_Size() int {
	return xxx_messageInfo_CommandsRequest.Size(m)
}
func (m *CommandsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommandsRequest proto.InternalMessageInfo

func (m *CommandsRequest) GetCategoryName() string {
	if m != nil {
		return m.CategoryName
	}
	return ""
}

type CommandsResponce struct {
	CommandNames         []string `protobuf:"bytes,1,rep,name=commandNames,proto3" json:"commandNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommandsResponce) Reset()         { *m = CommandsResponce{} }
func (m *CommandsResponce) String() string { return proto.CompactTextString(m) }
func (*CommandsResponce) ProtoMessage()    {}
func (*CommandsResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{3}
}

func (m *CommandsResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommandsResponce.Unmarshal(m, b)
}
func (m *CommandsResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommandsResponce.Marshal(b, m, deterministic)
}
func (m *CommandsResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommandsResponce.Merge(m, src)
}
func (m *CommandsResponce) XXX_Size() int {
	return xxx_messageInfo_CommandsResponce.Size(m)
}
func (m *CommandsResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_CommandsResponce.DiscardUnknown(m)
}

var xxx_messageInfo_CommandsResponce proto.InternalMessageInfo

func (m *CommandsResponce) GetCommandNames() []string {
	if m != nil {
		return m.CommandNames
	}
	return nil
}

type DescriptionRequest struct {
	CommandName          string   `protobuf:"bytes,1,opt,name=commandName,proto3" json:"commandName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescriptionRequest) Reset()         { *m = DescriptionRequest{} }
func (m *DescriptionRequest) String() string { return proto.CompactTextString(m) }
func (*DescriptionRequest) ProtoMessage()    {}
func (*DescriptionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{4}
}

func (m *DescriptionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescriptionRequest.Unmarshal(m, b)
}
func (m *DescriptionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescriptionRequest.Marshal(b, m, deterministic)
}
func (m *DescriptionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescriptionRequest.Merge(m, src)
}
func (m *DescriptionRequest) XXX_Size() int {
	return xxx_messageInfo_DescriptionRequest.Size(m)
}
func (m *DescriptionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescriptionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescriptionRequest proto.InternalMessageInfo

func (m *DescriptionRequest) GetCommandName() string {
	if m != nil {
		return m.CommandName
	}
	return ""
}

type DescriptionResponce struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Usage                string   `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	Examples             []string `protobuf:"bytes,3,rep,name=examples,proto3" json:"examples,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescriptionResponce) Reset()         { *m = DescriptionResponce{} }
func (m *DescriptionResponce) String() string { return proto.CompactTextString(m) }
func (*DescriptionResponce) ProtoMessage()    {}
func (*DescriptionResponce) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e16ccb8c5307b32, []int{5}
}

func (m *DescriptionResponce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescriptionResponce.Unmarshal(m, b)
}
func (m *DescriptionResponce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescriptionResponce.Marshal(b, m, deterministic)
}
func (m *DescriptionResponce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescriptionResponce.Merge(m, src)
}
func (m *DescriptionResponce) XXX_Size() int {
	return xxx_messageInfo_DescriptionResponce.Size(m)
}
func (m *DescriptionResponce) XXX_DiscardUnknown() {
	xxx_messageInfo_DescriptionResponce.DiscardUnknown(m)
}

var xxx_messageInfo_DescriptionResponce proto.InternalMessageInfo

func (m *DescriptionResponce) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *DescriptionResponce) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

func (m *DescriptionResponce) GetExamples() []string {
	if m != nil {
		return m.Examples
	}
	return nil
}

func init() {
	proto.RegisterType((*CategoriesRequest)(nil), "fetcher.CategoriesRequest")
	proto.RegisterType((*CategoriesResponce)(nil), "fetcher.CategoriesResponce")
	proto.RegisterType((*CommandsRequest)(nil), "fetcher.CommandsRequest")
	proto.RegisterType((*CommandsResponce)(nil), "fetcher.CommandsResponce")
	proto.RegisterType((*DescriptionRequest)(nil), "fetcher.DescriptionRequest")
	proto.RegisterType((*DescriptionResponce)(nil), "fetcher.DescriptionResponce")
}

func init() { proto.RegisterFile("services.proto", fileDescriptor_8e16ccb8c5307b32) }

var fileDescriptor_8e16ccb8c5307b32 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x09, 0x15, 0x94, 0x1e, 0x94, 0x96, 0x2b, 0x83, 0x09, 0x0c, 0x91, 0xc5, 0xd0, 0x29,
	0x03, 0x88, 0x0e, 0xac, 0x45, 0x9d, 0x10, 0x48, 0xf9, 0x06, 0xc6, 0x1c, 0x25, 0x12, 0x89, 0x43,
	0xec, 0x22, 0xf8, 0xec, 0x2c, 0x88, 0xd8, 0x69, 0x6c, 0x35, 0xa3, 0x7f, 0xf7, 0xe7, 0x3d, 0xbd,
	0x33, 0x9c, 0x6a, 0xaa, 0xbf, 0x72, 0x49, 0x3a, 0xad, 0x6a, 0x65, 0x14, 0x0e, 0xdf, 0xc8, 0xc8,
	0x77, 0xaa, 0xf9, 0x0c, 0xce, 0x96, 0xc2, 0xd0, 0x5a, 0xd5, 0x39, 0xe9, 0x8c, 0x3e, 0x37, 0xa4,
	0x0d, 0xbf, 0x07, 0xf4, 0xa1, 0xae, 0x54, 0x29, 0x09, 0xaf, 0x61, 0x2c, 0x2d, 0xfd, 0x79, 0x12,
	0x05, 0x69, 0x16, 0x25, 0x83, 0xf9, 0x28, 0x0b, 0x21, 0xbf, 0x83, 0xc9, 0x52, 0x15, 0x85, 0x28,
	0x5f, 0xdb, 0x75, 0xc8, 0xe1, 0xc4, 0xef, 0x61, 0x51, 0x12, 0xcd, 0x47, 0x59, 0xc0, 0xf8, 0x02,
	0xa6, 0xdd, 0x98, 0x13, 0xfc, 0x9f, 0xb3, 0xcc, 0xd7, 0x0b, 0x18, 0x5f, 0x00, 0x3e, 0x90, 0x96,
	0x75, 0x5e, 0x99, 0x5c, 0x95, 0xad, 0x62, 0x02, 0xc7, 0x5e, 0x97, 0x13, 0xf4, 0x11, 0x17, 0x30,
	0x0b, 0xe6, 0x9c, 0x24, 0x83, 0xa1, 0x54, 0xa5, 0xa1, 0xd2, 0xb8, 0xa1, 0xf6, 0x89, 0xe7, 0x70,
	0xb0, 0xd1, 0x62, 0x4d, 0x6c, 0xbf, 0xe1, 0xf6, 0x81, 0x31, 0x1c, 0xd1, 0xb7, 0x28, 0xaa, 0x0f,
	0xd2, 0x6c, 0xd0, 0xd8, 0xdb, 0xbe, 0x6f, 0x7e, 0xa3, 0xc0, 0xdb, 0xca, 0x26, 0x8e, 0x8f, 0x30,
	0x69, 0xc2, 0xef, 0x12, 0xc6, 0x38, 0x75, 0xe7, 0x48, 0x77, 0x6e, 0x11, 0x5f, 0xf6, 0xd6, 0xac,
	0x5d, 0xbe, 0x87, 0x2b, 0x18, 0xdb, 0x6d, 0x2e, 0x3c, 0x64, 0x5d, 0x7f, 0x78, 0x86, 0xf8, 0xa2,
	0xa7, 0xb2, 0xdd, 0xf3, 0x0c, 0xd3, 0xa6, 0xea, 0x19, 0xc6, 0x4e, 0x7a, 0x37, 0xe2, 0xf8, 0xaa,
	0xbf, 0xd8, 0x2e, 0x7c, 0x39, 0x6c, 0x3e, 0xda, 0xed, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12,
	0x63, 0xc6, 0xba, 0x7a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DescriptionFetcherClient is the client API for DescriptionFetcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DescriptionFetcherClient interface {
	FetchCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesResponce, error)
	FetchCommands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponce, error)
	FetchDescription(ctx context.Context, in *DescriptionRequest, opts ...grpc.CallOption) (*DescriptionResponce, error)
}

type descriptionFetcherClient struct {
	cc *grpc.ClientConn
}

func NewDescriptionFetcherClient(cc *grpc.ClientConn) DescriptionFetcherClient {
	return &descriptionFetcherClient{cc}
}

func (c *descriptionFetcherClient) FetchCategories(ctx context.Context, in *CategoriesRequest, opts ...grpc.CallOption) (*CategoriesResponce, error) {
	out := new(CategoriesResponce)
	err := c.cc.Invoke(ctx, "/fetcher.DescriptionFetcher/fetchCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *descriptionFetcherClient) FetchCommands(ctx context.Context, in *CommandsRequest, opts ...grpc.CallOption) (*CommandsResponce, error) {
	out := new(CommandsResponce)
	err := c.cc.Invoke(ctx, "/fetcher.DescriptionFetcher/fetchCommands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *descriptionFetcherClient) FetchDescription(ctx context.Context, in *DescriptionRequest, opts ...grpc.CallOption) (*DescriptionResponce, error) {
	out := new(DescriptionResponce)
	err := c.cc.Invoke(ctx, "/fetcher.DescriptionFetcher/fetchDescription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DescriptionFetcherServer is the server API for DescriptionFetcher service.
type DescriptionFetcherServer interface {
	FetchCategories(context.Context, *CategoriesRequest) (*CategoriesResponce, error)
	FetchCommands(context.Context, *CommandsRequest) (*CommandsResponce, error)
	FetchDescription(context.Context, *DescriptionRequest) (*DescriptionResponce, error)
}

// UnimplementedDescriptionFetcherServer can be embedded to have forward compatible implementations.
type UnimplementedDescriptionFetcherServer struct {
}

func (*UnimplementedDescriptionFetcherServer) FetchCategories(ctx context.Context, req *CategoriesRequest) (*CategoriesResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCategories not implemented")
}
func (*UnimplementedDescriptionFetcherServer) FetchCommands(ctx context.Context, req *CommandsRequest) (*CommandsResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchCommands not implemented")
}
func (*UnimplementedDescriptionFetcherServer) FetchDescription(ctx context.Context, req *DescriptionRequest) (*DescriptionResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchDescription not implemented")
}

func RegisterDescriptionFetcherServer(s *grpc.Server, srv DescriptionFetcherServer) {
	s.RegisterService(&_DescriptionFetcher_serviceDesc, srv)
}

func _DescriptionFetcher_FetchCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescriptionFetcherServer).FetchCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetcher.DescriptionFetcher/FetchCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescriptionFetcherServer).FetchCategories(ctx, req.(*CategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DescriptionFetcher_FetchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescriptionFetcherServer).FetchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetcher.DescriptionFetcher/FetchCommands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescriptionFetcherServer).FetchCommands(ctx, req.(*CommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DescriptionFetcher_FetchDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DescriptionFetcherServer).FetchDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fetcher.DescriptionFetcher/FetchDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DescriptionFetcherServer).FetchDescription(ctx, req.(*DescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DescriptionFetcher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fetcher.DescriptionFetcher",
	HandlerType: (*DescriptionFetcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "fetchCategories",
			Handler:    _DescriptionFetcher_FetchCategories_Handler,
		},
		{
			MethodName: "fetchCommands",
			Handler:    _DescriptionFetcher_FetchCommands_Handler,
		},
		{
			MethodName: "fetchDescription",
			Handler:    _DescriptionFetcher_FetchDescription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
